version: "3"
networks:
  file-server-network:
    driver: bridge

services:
  db:
    image: postgres
    container_name: server-docker-db
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_USER: DB_USER
      POSTGRES_DB: fileserver
    ports:
      - 5432:5432
    networks:
      - file-server-network

  backend:
    build:
      context: ./backend
    image: backend
    container_name: server-backend
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - file-server-network
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    image: frontend
    container_name: server-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - file-server-network
    env_file:
      - .env
