version: '3'
networks:
  file-server-network:
    driver: bridge

services:
  db:
    image: postgres
    container_name: server-docker-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: server
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    networks:
      - file-server-network
    expose:
      - 5433

  backend:
    build:
      context: ./backend
    image: file-server
    container_name: server-backend
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - file-server-network

  frontend:
    build:
      context: ./frontend
    image: server-front
    container_name: server-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - file-server-network
