#Change the location accordingly
#Remeber to add a sub folder in case of multiple profiles (owner)
#Preferably do not change this property
root.location=/File Server/owner

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

spring.datasource.driverClassName=org.postgresql.Driver
#Change database accordingly
spring.datasource.url=jdbc:postgresql://localhost:5432/server
#Enter your credentials
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=6666
