spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${dbHost}:5432/fileserver
    username: ${dbUser}
    password: ${dbPassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formate_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${serverIp}:8080/realms/file-server
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081
